// Configuración visual de cada tema festivo.
export const TEMAS_FESTIVOS = {
  navidad: {
    nombre: "Navidad",
    emoji: "🎄",
    badge: "Edición Navidad",
    titulo: "Feliz Navidad",
    mensaje: "Toda la familia del CD Bustarviejo os desea unas fiestas llenas de ilusión, familia… y muchos goles.",
    fondo: "from-[#062a1f] via-[#0f4a32] to-[#6b1111]",
    tituloGradiente: "from-white via-amber-100 to-amber-300",
    glow1: "bg-red-500/30",
    glow2: "bg-emerald-400/25",
    particulas: ["❄", "❅", "❆", "•"],
    colorParticula: "text-white",
  },
  reyes: {
    nombre: "Reyes Magos",
    emoji: "👑",
    badge: "Noche de Reyes",
    titulo: "Feliz Día de Reyes",
    mensaje: "Que Sus Majestades os traigan salud, alegría y una temporada inolvidable. ¡Habéis sido muy buenos!",
    fondo: "from-[#120f3a] via-[#3b1672] to-[#6b3a0a]",
    tituloGradiente: "from-amber-100 via-amber-300 to-yellow-500",
    glow1: "bg-amber-400/30",
    glow2: "bg-violet-500/30",
    particulas: ["✦", "✧", "★", "·"],
    colorParticula: "text-amber-300",
  },
  halloween: {
    nombre: "Halloween",
    emoji: "🎃",
    badge: "Noche de Halloween",
    titulo: "Feliz Halloween",
    mensaje: "Esta semana los porteros tienen miedo… ¡Truco o trato para todos los jugadores del club!",
    fondo: "from-[#0a0614] via-[#2e0a4f] to-[#6a2408]",
    tituloGradiente: "from-orange-200 via-orange-400 to-amber-500",
    glow1: "bg-orange-500/35",
    glow2: "bg-purple-600/30",
    particulas: ["🦇", "🍂", "🦇", "🕸️"],
    colorParticula: "",
  },
  carnaval: {
    nombre: "Carnaval",
    emoji: "🎭",
    badge: "Semana de Carnaval",
    titulo: "¡Es Carnaval!",
    mensaje: "Disfraces, música y color. Este fin de semana el club se viste de fiesta… ¿de qué vas a ir tú?",
    fondo: "from-[#9d174d] via-[#6d28d9] to-[#0e7490]",
    tituloGradiente: "from-yellow-100 via-pink-200 to-cyan-200",
    glow1: "bg-yellow-400/30",
    glow2: "bg-cyan-400/30",
    particulas: "confeti",
    colorParticula: "",
  },
};

export const CONFETI_COLORES = ["bg-pink-400", "bg-yellow-300", "bg-cyan-300", "bg-lime-300", "bg-violet-400", "bg-orange-400"];