/**
 * pages.config.js - Configuración de rutas.
 * Las páginas se cargan bajo demanda (React.lazy) para que la app no
 * descargue todas las pantallas al abrirse.
 */
import { lazy } from 'react';
import __Layout from './Layout.jsx';

export const PAGES = {
    "AdminAccessCodes": lazy(() => import('./pages/AdminAccessCodes')),
    "AdminChatsHub": lazy(() => import('./pages/AdminChatsHub')),
    "AdminGallery": lazy(() => import('./pages/AdminGallery')),
    "AdminStats": lazy(() => import('./pages/AdminStats')),
    "Announcements": lazy(() => import('./pages/Announcements')),
    "Anuncios": lazy(() => import('./pages/Anuncios')),
    "AppAnalytics": lazy(() => import('./pages/AppAnalytics')),
    "BirthdayPreview": lazy(() => import('./pages/BirthdayPreview')),
    "BoardTasks": lazy(() => import('./pages/BoardTasks')),
    "CalendarAndSchedules": lazy(() => import('./pages/CalendarAndSchedules')),
    "CategoryConfigAdmin": lazy(() => import('./pages/CategoryConfigAdmin')),
    "CategoryManagement": lazy(() => import('./pages/CategoryManagement')),
    "CentroCompeticion": lazy(() => import('./pages/CentroCompeticion')),
    "CentroCompeticionTecnico": lazy(() => import('./pages/CentroCompeticionTecnico')),
    "ChatAnalyticsDashboard": lazy(() => import('./pages/ChatAnalyticsDashboard')),
    "ChatNotificationAuditPage": lazy(() => import('./pages/ChatNotificationAuditPage')),
    "ChatTestConsole": lazy(() => import('./pages/ChatTestConsole')),
    "Chatbot": lazy(() => import('./pages/Chatbot')),
    "CheckinTablet": lazy(() => import('./pages/CheckinTablet')),
    "ClubMembersManagement": lazy(() => import('./pages/ClubMembersManagement')),
    "ClubMembership": lazy(() => import('./pages/ClubMembership')),
    "ClubStats": lazy(() => import('./pages/ClubStats')),
    "CoachAttendance": lazy(() => import('./pages/CoachAttendance')),
    "CoachCallups": lazy(() => import('./pages/CoachCallups')),
    "CoachChatSettings": lazy(() => import('./pages/CoachChatSettings')),
    "CoachChatsHub": lazy(() => import('./pages/CoachChatsHub')),
    "CoachDashboard": lazy(() => import('./pages/CoachDashboard')),
    "CoachEvaluationReports": lazy(() => import('./pages/CoachEvaluationReports')),
    "CoachParentChat": lazy(() => import('./pages/CoachParentChat')),
    "CoachProfile": lazy(() => import('./pages/CoachProfile')),
    "CoachProfiles": lazy(() => import('./pages/CoachProfiles')),
    "CoachStandingsAnalysis": lazy(() => import('./pages/CoachStandingsAnalysis')),
    "CompetitionChecklist": lazy(() => import('./pages/CompetitionChecklist')),
    "ContactRequests": lazy(() => import('./pages/ContactRequests')),
    "CoordinatorChat": lazy(() => import('./pages/CoordinatorChat')),
    "CoordinatorChatsHub": lazy(() => import('./pages/CoordinatorChatsHub')),
    "CoordinatorDashboard": lazy(() => import('./pages/CoordinatorDashboard')),
    "CoordinatorSettings": lazy(() => import('./pages/CoordinatorSettings')),
    "CustomPaymentPlans": lazy(() => import('./pages/CustomPaymentPlans')),
    "DeleteAccount": lazy(() => import('./pages/DeleteAccount')),
    "DocumentManagement": lazy(() => import('./pages/DocumentManagement')),
    "EmailTemplates": lazy(() => import('./pages/EmailTemplates')),
    "EventManagement": lazy(() => import('./pages/EventManagement')),
    "ExerciseLibrary": lazy(() => import('./pages/ExerciseLibrary')),
    "FamilyChats": lazy(() => import('./pages/FamilyChats')),
    "FamilyChatsHub": lazy(() => import('./pages/FamilyChatsHub')),
    "FamilyGuide": lazy(() => import('./pages/FamilyGuide')),
    "FederationSignatures": lazy(() => import('./pages/FederationSignatures')),
    "FederationSignaturesAdmin": lazy(() => import('./pages/FederationSignaturesAdmin')),
    "FeedbackManagement": lazy(() => import('./pages/FeedbackManagement')),
    "FemeninoInterests": lazy(() => import('./pages/FemeninoInterests')),
    "Gallery": lazy(() => import('./pages/Gallery')),
    "Home": lazy(() => import('./pages/Home')),
    "InstallSuccessPreview": lazy(() => import('./pages/InstallSuccessPreview')),
    "InvitationRequests": lazy(() => import('./pages/InvitationRequests')),
    "JoinFemenino": lazy(() => import('./pages/JoinFemenino')),
    "JoinReferral": lazy(() => import('./pages/JoinReferral')),
    "JuniorMailbox": lazy(() => import('./pages/JuniorMailbox')),
    "JuniorMailboxAdmin": lazy(() => import('./pages/JuniorMailboxAdmin')),
    "LopiviAdmin": lazy(() => import('./pages/LopiviAdmin')),
    "LotteryManagement": lazy(() => import('./pages/LotteryManagement')),
    "ManualAcceso": lazy(() => import('./pages/ManualAcceso')),
    "MarketListingDetail": lazy(() => import('./pages/MarketListingDetail')),
    "MatchApp": lazy(() => import('./pages/MatchApp')),
    "MatchMinutesTracker": lazy(() => import('./pages/MatchMinutesTracker')),
    "MatchResults": lazy(() => import('./pages/MatchResults')),
    "MedicalRecords": lazy(() => import('./pages/MedicalRecords')),
    "MemberCardDisplay": lazy(() => import('./pages/MemberCardDisplay')),
    "MemberManagement": lazy(() => import('./pages/MemberManagement')),
    "Mercadillo": lazy(() => import('./pages/Mercadillo')),
    "MinorDashboard": lazy(() => import('./pages/MinorDashboard')),
    "MinorPreview": lazy(() => import('./pages/MinorPreview')),
    "NotificationPreferences": lazy(() => import('./pages/NotificationPreferences')),
    "OnboardingPreview": lazy(() => import('./pages/OnboardingPreview')),
    "PWASetup": lazy(() => import('./pages/PWASetup')),
    "ParentCallups": lazy(() => import('./pages/ParentCallups')),
    "ParentCoachChat": lazy(() => import('./pages/ParentCoachChat')),
    "ParentCoordinatorChat": lazy(() => import('./pages/ParentCoordinatorChat')),
    "ParentDashboard": lazy(() => import('./pages/ParentDashboard')),
    "ParentDirectMessages": lazy(() => import('./pages/ParentDirectMessages')),
    "ParentDocuments": lazy(() => import('./pages/ParentDocuments')),
    "ParentEventRSVP": lazy(() => import('./pages/ParentEventRSVP')),
    "ParentGallery": lazy(() => import('./pages/ParentGallery')),
    "ParentLottery": lazy(() => import('./pages/ParentLottery')),
    "ParentOrders": lazy(() => import('./pages/ParentOrders')),
    "ParentPayments": lazy(() => import('./pages/ParentPayments')),
    "ParentPlayers": lazy(() => import('./pages/ParentPlayers')),
    "ParentSystemMessages": lazy(() => import('./pages/ParentSystemMessages')),
    "ParentTrainingSchedules": lazy(() => import('./pages/ParentTrainingSchedules')),
    "PaymentHistory": lazy(() => import('./pages/PaymentHistory')),
    "PaymentReminders": lazy(() => import('./pages/PaymentReminders')),
    "Payments": lazy(() => import('./pages/Payments')),
    "PaymentsDashboard": lazy(() => import('./pages/PaymentsDashboard')),
    "PlayerDashboard": lazy(() => import('./pages/PlayerDashboard')),
    "Players": lazy(() => import('./pages/Players')),
    "PlayerEvaluations": lazy(() => import('./pages/PlayerEvaluations')),
    "PlayerProfile": lazy(() => import('./pages/PlayerProfile')),
    "PlayerRenewal": lazy(() => import('./pages/PlayerRenewal')),
    "PlayerStatsPreview": lazy(() => import('./pages/PlayerStatsPreview')),
    "PwaEntry": lazy(() => import('./pages/PwaEntry')),
    "ReferralManagement": lazy(() => import('./pages/ReferralManagement')),
    "Reminders": lazy(() => import('./pages/Reminders')),
    "RenewalDashboard": lazy(() => import('./pages/RenewalDashboard')),
    "RffmMonitor": lazy(() => import('./pages/RffmMonitor')),
    "Schedules": lazy(() => import('./pages/Schedules')),
    "SeasonManagement": lazy(() => import('./pages/SeasonManagement')),
    "Shop": lazy(() => import('./pages/Shop')),
    "Sponsorships": lazy(() => import('./pages/Sponsorships')),
    "StaffChat": lazy(() => import('./pages/StaffChat')),
    "Surveys": lazy(() => import('./pages/Surveys')),
    "TacticsBoard": lazy(() => import('./pages/TacticsBoard')),
    "TeamAttendanceEvaluation": lazy(() => import('./pages/TeamAttendanceEvaluation')),
    "TeamRosters": lazy(() => import('./pages/TeamRosters')),
    "Tienda": lazy(() => import('./pages/Tienda')),
    "TrainingSchedules": lazy(() => import('./pages/TrainingSchedules')),
    "TreasurerDashboard": lazy(() => import('./pages/TreasurerDashboard')),
    "TreasurerFinancialPanel": lazy(() => import('./pages/TreasurerFinancialPanel')),
    "UploadDiagnostics": lazy(() => import('./pages/UploadDiagnostics')),
    "UserManagement": lazy(() => import('./pages/UserManagement')),
    "Voluntariado": lazy(() => import('./pages/Voluntariado')),
    "WebContacts": lazy(() => import('./pages/WebContacts')),
}

export const pagesConfig = {
    mainPage: "Home",
    Pages: PAGES,
    Layout: __Layout,
};